name: AmazingTowers

author: Pato14, katanya04

version: '${project.version}'
depend: [AnotherGUIPlugin]
softdepend: [Vault, PlaceholderAPI]

main: mx.towers.pato14.AmazingTowers


commands:
  towers: 
    aliases: [tower, tw, tt]
  kits:
    aliases: [kit]
  lobby:
    aliases: [hub, exit, salir, volver, leave, back]
  ready:
    aliases: [listo]
  list:
    aliases: [lista]
  AmazingTowers:
    aliases: [at]