# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta3            #> #
# <#             Author: Pato14, katanya04            #> #
# +###----------------------------------------------###+ #

lobbyItems:
  selectGame:
    name: "&b&lUnirse a una partida"
    position: 0
  quit:
    name: "&c&lVolver al lobby"
    position: 8

options:
  cancelWeatherUpdates: true
  portalsToGame: true
  chat:
    enabled: true
    format:
      defaultChat: '%vault_prefix% &f%player% &8: &f%msg%'

name: "Lobby"