name: AmazingTowers

author: Pato14, katanya04

version: 3.0_beta3
depend: [NametagEdit, BossBarAPI, AnotherGUIPlugin]
softdepend: [Vault, PlaceholderAPI]

main: mx.towers.pato14.AmazingTowers


commands:
  towers: 
    aliases: [tower, tw, tt]