# +###----------------------------------------------###+ #
# <#               AmazingTowers - v2.3b              #> #
# <#             Author: Pato14, Marco2124            #> #
# +###----------------------------------------------###+ #


Options:

  Rewards:

    vault: true
    reward:
      kill: 2
      win: 20
      point: 10
      forplay: 5
    messages:
      kill: '&a+%coins% &7monedas'
      win: '&a+%coins% &7monedas'
      point: '&a+%coins% &7monedas'
      forplay: '&a+%coins% &7monedas'

  chat:
    enabled: true
    format:
      defaultChat: '%vault_prefix% &f%player% &8: &f%msg%'
      teamChat: '%team_color%&l%team_prefix% &f%player% &8: &f%msg%'
      globalChat: '%team_color%&l[GLOBAL] &f%player% &7: &f%msg%'

  instant_respawn: true

  refill_chests:
    enabled: true
    message_scoreboard: '&cCofres rellenados!'
    timer_refill: 0;50
    message_refill: true

  protect_leatherArmor: true

  weather_cancel: true

  chestsTeam: true

  command: stop

  detection_playerinPool: 5

  gameStart:
    min-players: 2
    timer-start: 20

  Points: 10

  timerEndSeconds: 10

  generator_timePerSecond: 5


Items:

  hotbarItems:
    joinTeams:
      name: '&3&lEscoger equipo'
      position: 0
    kits:
      name: '&3&lEscoger kit'
      position: 1
    quit:
      name: '&c&lVolver al lobby'
      position: 8

  menuItems:
    joinTeam: '%team_color%&lUnirse al equipo %team_name%'
    spectator: '&7&lModo espectador'

  buyKitMenuName: '&a&lComprar kit'
  acceptBuy: '&a&lComprar'
  denyBuy: '&c&lNo comprar'



Teams:

  numberOfTeams: 2

  teamNames:
    red: 'rojo'
    blue: 'azul'
    green: 'verde'
    yellow: 'amarillo'
    white: 'blanco'
    black: 'negro'
    orange: 'naranja'
    purple: 'morado'
    spectator: 'espectador'

  prefixes:
    red: '[ROJO]'
    blue: '[AZUL]'
    green: '[VERDE]'
    yellow: '[AMARILLO]'
    white: '[BLANCO]'
    black: '[NEGRO]'
    orange: '[NARANJA]'
    purple: '[MORADO]'
    default: ''