# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta1            #> #
# <#             Author: Pato14, Marco2124            #> #
# +###----------------------------------------------###+ #

options:

  lobby:
    activated: true
    worldName: lobby

  instances:
    amount: 1

  mysql:
    active: false
    hostname:
    port:
    database:
    user:
    password:

  bungeecord:
    enabled: false
    server_name: LobbyTowers

  rewards:
    vault: false


permissions:

  password:
    organizer:

globalChat:
  activated: true
  format: '%vault_prefix% &a&l[%instance_name%] &f%player% &7: &f%msg%'