# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta1            #> #
# <#             Author: Pato14, Marco2124            #> #
# +###----------------------------------------------###+ #

options:

  lobby:
    activated: true
    worldName: lobby

  instances:
    amount: 1

  database:
    active: false
    hostname:
    port:
    database:
    user:
    password:
    tableNames:
      - 'table1'

  bungeecord:
    enabled: false
    server_name:

  rewards:
    vault: false


permissions:
  password:
    organizer:

globalChat:
  activated: true
  format: '%vault_prefix% &a&l[%instance_name%] &f%player% &7: &f%msg%'