name: AmazingTowers

author: Pato14, Marco2124

version: 3.0_beta1
depend: [NametagEdit, BossBarAPI]
softdepend: [Vault, PlaceholderAPI]

main: mx.towers.pato14.AmazingTowers


commands:
  towers: 
    aliases: [tower, tw, tt]