# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta1            #> #
# <#             Author: Pato14, Marco2124            #> #
# +###----------------------------------------------###+ #


options:

  rewards:
    vault: true
    reward:
      kill: 2
      win: 20
      point: 10
      match: 5
    messages:
      kill: '&a+%coins% &7monedas'
      win: '&a+%coins% &7monedas'
      point: '&a+%coins% &7monedas'
      match: '&a+%coins% &7monedas'

  chat:
    enabled: true
    format:
      defaultChat: '%vault_prefix% &f%player% &8: &f%msg%'
      teamChat: '%team_color%&l%team_prefix% &f%player% &8: &f%msg%'
      globalChat: '%team_color%&l[GLOBAL] &f%player% &7: &f%msg%'

  instantRespawn: true

  chests:
    lockChestsToOtherTeams: true
    refillChests:
      enabled: true
      messageOnScoreboard: '&cCofres rellenados!'
      refillTime: 0;50
      sendMessageOnRefill: true

  canNotDropLeatherArmor: true

  cancelWeatherUpdates: true

  sendPlayerToAnotherInstanceAtTheEnd: true

  ticksPerPoolsCheck: 5

  gameStart:
    minPlayers: 2
    timerStart: 20

  pointsToWin: 10

  timerEndSeconds: 10

  generatorSpeedInSeconds: 5


lobbyItems:

  hotbarItems:
    selectTeam:
      name: '&3&lEscoger equipo'
      position: 0
    selectKit:
      name: '&3&lEscoger kit'
      position: 1
    modifyGameSettings:
      name: '&3&lModificar ajustes'
      position: 7
    quit:
      name: '&c&lVolver al lobby'
      position: 8

  menuItems:
    joinTeam: '%team_color%&lUnirse al equipo %team_name%'
    spectator: '&7&lModo espectador'

  buyKitMenuName: '&a&lComprar kit'
  acceptBuy: '&a&lComprar'
  denyBuy: '&c&lNo comprar'

settingsBook:
  kickAll:
    name: '&7&lKickear a todos los jugadores'
    kickMessage: 'Todos los jugadores han sido kickeados de esta partida'
  setRules: '&7&lCambiar las reglas'
  continueCount: '&7&lContinuar la cuenta atras'
  setWhitelist: '&7&lWhitelist'
  setBlacklist: '&7&lBlacklist'
  startImmediately: '&7&lEmpezar ya la partida'
  stopCount: '&7&lParar la cuenta atras'
  setTimer: '&7&lTimer'
  saveSettings:
    name: '&d&lGuardar ajustes'
    saveMessage: 'Ajustes guardados correctamente'
    noChangesMessage: 'No hay ningún cambio que guardar'



teams:

  numberOfTeams: 2

  teamNames:
    red: 'rojo'
    blue: 'azul'
    green: 'verde'
    yellow: 'amarillo'
    white: 'blanco'
    black: 'negro'
    orange: 'naranja'
    purple: 'morado'
    spectator: 'espectador'

  prefixes:
    red: '[ROJO]'
    blue: '[AZUL]'
    green: '[VERDE]'
    yellow: '[AMARILLO]'
    white: '[BLANCO]'
    black: '[NEGRO]'
    orange: '[NARANJA]'
    purple: '[MORADO]'
    default: ''