# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta2            #> #
# <#             Author: Pato14, katanya04            #> #
# +###----------------------------------------------###+ #


rules:
  grief: 'false'
  protectPoint: 'true'
  emerald: 'true'
  redstone: 'true'
  coal: 'true'
  lapislazuli: 'true'
  balancedTeams: 'true'
  bow: 'true'
  ironArmor: 'true'
  water: 'true'
  potsAndApple: 'true'
  enderPearl: 'true'
  tnt: 'true'
  enchants: 'true'
  kits: 'true'
  bedwarsStyle: 'false'
whitelist:
  activated: 'false'
  players:
    - '<empty>'
blacklist:
  activated: 'false'
  players:
    - '<empty>'
timer:
  activated: 'false'
  time: '30:00'
  message: 'Tiempo: %time%'
database:
  database: '<db_name>'
refill:
  activated: 'true'
  time: '01:00'
points:
  pointsToWin: '10'
  livesBedwarsMode: '10'
itemOnKill:
  activated: 'false'
  item: ''
generators:
  activated: 'true'
  waitTimeSeconds: '5'