# +###----------------------------------------------###+ #
# <#               AmazingTowers - v2.3b              #> #
# <#             Author: Pato14, Marco2124            #> #
# +###----------------------------------------------###+ #

options:

  instances:
    amount: 1

  mysql:
    active: false
    hostname:
    port:
    database:
    user:
    password:

  bungeecord:
    enabled: false
    server_name: LobbyTowers

  rewards:
    vault: false


permissions:

  password:
    organizer: