# +###----------------------------------------------###+ #
# <#            AmazingTowers - v3.0_beta3            #> #
# <#             Author: Pato14, katanya04            #> #
# +###----------------------------------------------###+ #

options:

  lobby:
    activated: true
    worldName: lobby

  instances:
    amount: 1

  database:
    active: false
    hostname:
    port:
    database:
    user:
    password:
    tableNames:
      - 'table1'

  bungeecord:
    enabled: false
    server_name:

  rewards:
    vault: false

  logger:
    activated: false
    maxTimeHoursPerFile: 12
    logTowersCommand: false
    logSQLCalls: false

    #Posible values: READ, WRITE, ALL. Will default to WRITE
    SQLCallType: 'WRITE'

    #Posible values: ADMIN, ORGANIZER, NONE. Will default to ADMIN
    permLevelToLog: 'ORGANIZER'


permissions:
  password:
    organizer:

globalChat:
  activated: true
  format: '%vault_prefix% &a&l[%instance_name%] &f%player% &7: &f%msg%'