name: AmazingTowers

author: Pato14, katanya04

version: 3.0_beta3
depend: [BossBarAPI, AnotherGUIPlugin]
softdepend: [Vault, PlaceholderAPI]

main: mx.towers.pato14.AmazingTowers


commands:
  towers: 
    aliases: [tower, tw, tt]
  kits:
    aliases: [kit]
  lobby:
    aliases: [hub, exit, salir, volver, leave, back]
  ready:
    aliases: [listo]
  listall:
    aliases: [listatodos]